import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import TanStackProvider from "@/components/providers/TanStackProvider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OTV-Rankings",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TanStackProvider>
      <html lang="en" >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}>
          <Navbar />
          {children}
          <Footer />
          <Toaster position="bottom-right" />
        </body>
      </html>
    </TanStackProvider>
  );
}
